spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/singlebungle?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

openai:
  model: gpt-4o
  api:
    key: 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
    url: https://api.openai.com

google:
  vision:
    api-key: AIzaSyDqwJw6qknWfRBqmdzVyPuvpxi2zDh2o1s

server:
  port: 8080
  address: localhost
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health